PlacesTodo/Models/Folder.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace PlacesTodo.Models
{
    public class Folder
    {
        public int Id { get; set; }

        public int? ParentId { get; set; }
        public Folder? Parent { get; set; }

        public List<Folder>? Children { get; set; }
        public List<Item>? Tasks { get; set; }

        [DisplayName("Name")]
        [MinLength(2), MaxLength(20)]
        public string Name { get; set; }
    }
}

PlacesTodo/Controllers/FoldersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlacesTodo.Context;
using PlacesTodo.Models;

namespace PlacesTodo.Controllers
{
    [Authorize]
    public class FoldersController : GenericController<Folder>
    {
        public FoldersController(AppDBContext context, UserManager<User> userManager) : base(context, userManager) { }

        // GET: FoldersController
        public async Task<IActionResult> Index()
        {
            var folders = _context.Folders.Include(f => f.Children).Include(f => f.Tasks).ToList();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            return View(folders.Where(v => v.ParentId == null && v.Id == user.FolderId).FirstOrDefault());
        }

        // GET: FoldersController/Create
        public ActionResult Create(int parentId)
        {
            ViewBag.ParentName = _context.Folders.Where(v => v.Id == parentId).FirstOrDefault().Name;
            
            return View(new Folder { ParentId = parentId });
        }

        //POST: FoldersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public override async Task<IActionResult> Delete(int id, bool diff = false)
        {
            DeleteWithChildren(id);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private void DeleteWithChildren(int id)
        {
            Folder folder = _context.Folders.FirstOrDefault(v => v.Id == id);

            if (folder == null) return;

            List<Folder> children = _context.Folders.Where(v => v.ParentId == id).ToList();
            if (children != null && children.Count > 0)
            {
                foreach (Folder child in children)
                {
                    DeleteWithChildren(child.Id);
                }
            }
            _context.Remove(folder);
        }
    }
}

PlacesTodo/Controllers/TasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlacesTodo.Context;
using PlacesTodo.Models;

namespace PlacesTodo.Controllers
{
    [Authorize]
    public class TasksController : GenericController<Item>
    {
        public TasksController(AppDBContext context, UserManager<User> userManager) : base(context, userManager) {}

        public IActionResult Index()
        {
            return View();
        }

        public ActionResult Create(int parentId)
        {
            ViewBag.ParentName = _context.Folders.Where(v => v.Id == parentId).FirstOrDefault().Name;

            return View(new Item { ParentId = parentId });
        }
    }
}

PlacesTodo/Views/Folders/Create.cshtml
@model PlacesTodo.Models.Folder

<div class="text-center">
    <h1 class="display-4">Create Folder</h1>
</div>

<div>
    <p>Parent: @ViewBag.ParentName</p>
    <form asp-action="Create" style="block">
        Name:
        <input type="text" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
        <br />
        <input type="hidden" asp-for="ParentId" value="@Model.ParentId" />
        <input type="submit" value="Create" />
    </form>
    <a href="@Url.Action("Index", "Folders")">Cancel</a>
</div>

PlacesTodo/Views/Folders/Delete.cshtml
@model PlacesTodo.Models.Folder

<div class="text-center">
    <h1 class="display-4">Create Folder</h1>
</div>

<div>
    Are you sure you want to delete: @Model.Name and all of its children?
</div>

<form asp-controller="Folders" asp-action="Delete">
    <input type="hidden" name="folderId" value="@Model.Id" />
    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-controller="Folders" asp-action="Index">No</a>
</form>

PlacesTodo/Views/Folders/Edit.cshtml
@model PlacesTodo.Models.Folder

<form asp-action="Edit" style="block">
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    Name:
    <input type="text" asp-for="Name" />
    <span asp-validation-for="Name" class="text-danger"></span>
    <br />
    <input type="hidden" asp-for="ParentId" value="@Model.ParentId" />
    <input type="submit" value="Submit" />
</form>
<a href="@Url.Action("Index", "Folders")">Cancel</a>

PlacesTodo/Views/Folders/Index.cshtml
@model PlacesTodo.Models.Folder

<div class="text-center">
    <h1 class="display-4">Folders</h1>
</div>

@{
    const int folderIndent = 20;
    const int taskIndent = 10;

    void ShowFolder(Folder folder, int depth)
    {
        <div style="margin-left:@Html.Raw(depth * 20)px; color:lightgrey">
            @if(depth == 0)
            {
                @Context.User.Identity.Name; 
                @Html.Raw("'s Tasks");
                <a href="@Url.Action("Create","Folders", new {parentId = folder.Id})">New Folder</a>
                <a href="@Url.Action("Create","Tasks", new {parentId = folder.Id})">New Task</a>
            }
            else
            {
                @folder.Name;
                <a href="@Url.Action("Edit","Folders", new {id = folder.Id})">Edit</a>
                <a href="@Url.Action("Delete","Folders", new {id = folder.Id})">Delete</a>
                <a href="@Url.Action("Create","Folders", new {parentId = folder.Id})">New Folder</a>
                <a href="@Url.Action("Create","Tasks", new {parentId = folder.Id})">New Task</a>
            }


            @if (folder.Tasks != null && folder.Tasks.Count > 0)
            {
                foreach(Item task in folder.Tasks)
                {
                <div style="margin-left:10px; color:white">
                    - @task.Name
                        <p style="display:inline; color:green">@task.DueDate.Date.ToString("dd/mm/yyyy")</p>
                    <a href="@Url.Action("Edit","Tasks", new {id = task.Id})">Edit</a>
                    <a href="@Url.Action("Delete","Tasks", new {id = task.Id})">Delete</a>
                    <p style="font-size:15px; margin-left:20px">@task.Description</p>
                </div>
                }
            }
            
        </div>

        

        if (folder.Children == null || folder.Children.Count == 0)
            return;

        @foreach(Folder child in folder.Children)
        {
            ShowFolder(child, depth + 1);
        }
    }

    ShowFolder(Model, 0);
}