PlacesTodo/Controllers/AccountsController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PlacesTodo.Context;
using PlacesTodo.Models;
using System.Security.Claims;

namespace PlacesTodo.Controllers
{
    public class AccountsController : Controller
    {
        protected readonly AppDBContext _context;
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;

        public AccountsController(AppDBContext context, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterViewModel registerModel)
        {
            if (ModelState.IsValid)
            {
                Folder userRoot = new Folder() { Name = registerModel.Name + "_root" };
                _context.Folders.Add(userRoot);
                await _context.SaveChangesAsync();
                User user = new User() { UserName = registerModel.Name, FolderId = userRoot.Id };
                var result = await _userManager.CreateAsync(user, registerModel.Password!);
                if (result.Succeeded)
                {
                    Claim userClaim = new Claim("User", "Standard");
                    await _userManager.AddClaimAsync(user, userClaim);
                    await _signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View();
        }

        [HttpGet]
        public IActionResult Login(string returnUrl = "")
        {
            ViewData["ReturnUrl"] = returnUrl;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel loginModel, string returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                var result = await _signInManager.PasswordSignInAsync(loginModel.Name!, loginModel.Password!, loginModel.RememberMe, false);
                if (result.Succeeded)
                {
                    return Redirect(returnUrl);
                }
            }
            return View();
        }

        [HttpGet]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(string returnUrl = "")
        {
            await _signInManager.SignOutAsync();
            return Redirect(returnUrl);
        }
    }
}

PlacesTodo/Controllers/FoldersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PlacesTodo.Context;
using PlacesTodo.Models;

namespace PlacesTodo.Controllers
{
    [Authorize]
    public class FoldersController : GenericController<Folder>
    {
        public FoldersController(AppDBContext context, UserManager<User> userManager) : base(context, userManager) { }

        // GET: FoldersController
        public async Task<IActionResult> Index()
        {
            var folders = _context.Folders.Include(f => f.Children).Include(f => f.Tasks).ToList();
            var user = await _userManager.GetUserAsync(HttpContext.User);

            return View(folders.Where(v => v.ParentId == null && v.Id == user.FolderId).FirstOrDefault());
        }

        // GET: FoldersController/Create
        public ActionResult Create(int parentId)
        {
            ViewBag.ParentName = _context.Folders.Where(v => v.Id == parentId).FirstOrDefault().Name;
            
            return View(new Folder { ParentId = parentId });
        }

        //POST: FoldersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public override async Task<IActionResult> Delete(int id, bool diff = false)
        {
            DeleteWithChildren(id);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private void DeleteWithChildren(int id)
        {
            Folder folder = _context.Folders.FirstOrDefault(v => v.Id == id);

            if (folder == null) return;

            List<Folder> children = _context.Folders.Where(v => v.ParentId == id).ToList();
            if (children != null && children.Count > 0)
            {
                foreach (Folder child in children)
                {
                    DeleteWithChildren(child.Id);
                }
            }
            _context.Remove(folder);
        }
    }
}

PlacesTodo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PlacesTodo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PlacesTodo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" style="color:white" asp-area="" asp-controller="Home" asp-action="Index">PlacesTodo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" style="color:white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:white" asp-area="" asp-controller="Folders" asp-action="Index">Tasks</a>
                        </li>
                    </ul>
                    <div class="mr-2" style="margin-right: 50px">
                        @if (Context.User.Identity != null && Context.User.Identity.IsAuthenticated)
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" style="color:white" asp-controller="Accounts" asp-action="Details">@Context.User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color:white" asp-controller="Accounts" asp-method="POST" asp-action="Logout" asp-route-returnUrl="@Context.Request.Path">Logout</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color:white" asp-controller="Admin" asp-action="Index">Admin</a>
                                </li>
                            </ul>
                        }
                        else
                        {
                             <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link" style="color:white" asp-controller="Accounts" asp-action="Login" asp-route-returnUrl="@Context.Request.Path">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" style="color:white" asp-controller="Accounts" asp-action="Register" asp-route-returnUrl="@Context.Request.Path">Register</a>
                                </li>
                            </ul>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PlacesTodo - Jakub Szymanik
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>